-- Message Queue Management Module Migration
-- 消息队列管理一期：实例纳管、元数据同步、消费诊断、消息采样审计

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

CREATE TABLE IF NOT EXISTS `mq_instances` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `name` varchar(100) NOT NULL COMMENT '实例名称',
  `mq_type` varchar(30) NOT NULL COMMENT '消息队列类型',
  `engine` varchar(50) DEFAULT NULL COMMENT '具体引擎',
  `version` varchar(120) DEFAULT NULL COMMENT '版本',
  `endpoint` varchar(500) NOT NULL COMMENT '连接地址，多个地址逗号分隔',
  `management_url` varchar(500) DEFAULT NULL COMMENT '管理API地址',
  `port` int DEFAULT 0 COMMENT '默认端口',
  `credential_id` bigint unsigned DEFAULT 0 COMMENT '凭据ID',
  `tls_enabled` tinyint(1) DEFAULT 0 COMMENT '是否启用TLS',
  `connection_params` text COMMENT '连接参数JSON',
  `status` varchar(20) DEFAULT 'enabled' COMMENT '状态 enabled/disabled',
  `health_status` varchar(20) DEFAULT 'unknown' COMMENT '健康状态',
  `environment` varchar(50) DEFAULT NULL COMMENT '环境',
  `business_system` varchar(100) DEFAULT NULL COMMENT '业务系统',
  `owner` varchar(100) DEFAULT NULL COMMENT '负责人',
  `tags` varchar(500) DEFAULT NULL COMMENT '标签',
  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
  `last_test_at` datetime(3) DEFAULT NULL COMMENT '最近测试时间',
  `last_sync_at` datetime(3) DEFAULT NULL COMMENT '最近同步时间',
  `last_metric_at` datetime(3) DEFAULT NULL COMMENT '最近指标采集时间',
  PRIMARY KEY (`id`),
  KEY `idx_mq_instances_deleted_at` (`deleted_at`),
  KEY `idx_mq_instances_mq_type` (`mq_type`),
  KEY `idx_mq_instances_status` (`status`),
  KEY `idx_mq_instances_health_status` (`health_status`),
  KEY `idx_mq_instances_environment` (`environment`),
  KEY `idx_mq_instances_credential_id` (`credential_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ实例表';

CREATE TABLE IF NOT EXISTS `mq_instance_permissions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `role_id` bigint unsigned NOT NULL COMMENT '角色ID',
  `instance_id` bigint unsigned NOT NULL COMMENT 'MQ实例ID',
  `permissions` int unsigned NOT NULL DEFAULT 1 COMMENT '权限位图',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mq_instance_permission` (`role_id`, `instance_id`),
  KEY `idx_mq_instance_permissions_deleted_at` (`deleted_at`),
  KEY `idx_mq_instance_permissions_instance_id` (`instance_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ实例对象级权限';

CREATE TABLE IF NOT EXISTS `mq_brokers` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `broker_name` varchar(160) NOT NULL COMMENT 'Broker名称',
  `broker_id` varchar(120) DEFAULT NULL COMMENT 'Broker ID',
  `host` varchar(255) DEFAULT NULL COMMENT '主机',
  `port` int DEFAULT 0 COMMENT '端口',
  `role` varchar(60) DEFAULT NULL COMMENT '角色',
  `status` varchar(60) DEFAULT NULL COMMENT '状态',
  `version` varchar(120) DEFAULT NULL COMMENT '版本',
  `rack` varchar(120) DEFAULT NULL COMMENT 'Rack',
  `zone` varchar(120) DEFAULT NULL COMMENT '可用区',
  `metadata_json` text COMMENT '原始元数据JSON',
  `last_sync_at` datetime(3) DEFAULT NULL COMMENT '最近同步时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mq_broker_unique` (`instance_id`, `broker_name`),
  KEY `idx_mq_brokers_deleted_at` (`deleted_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ Broker元数据';

CREATE TABLE IF NOT EXISTS `mq_resources` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `resource_type` varchar(40) NOT NULL COMMENT '资源类型',
  `namespace` varchar(255) DEFAULT '' COMMENT '命名空间/vhost/tenant',
  `name` varchar(255) NOT NULL COMMENT '资源名称',
  `full_name` varchar(512) DEFAULT NULL COMMENT '完整名称',
  `durable` tinyint(1) DEFAULT 0 COMMENT '是否持久化',
  `partition_count` int DEFAULT 0 COMMENT '分区数',
  `replica_count` int DEFAULT 0 COMMENT '副本数',
  `message_count` bigint DEFAULT 0 COMMENT '消息量',
  `backlog` bigint DEFAULT 0 COMMENT '堆积',
  `produced_rate` double DEFAULT 0 COMMENT '生产速率',
  `consumed_rate` double DEFAULT 0 COMMENT '消费速率',
  `consumer_count` int DEFAULT 0 COMMENT '消费者数',
  `config_json` text COMMENT '配置JSON',
  `metadata_json` text COMMENT '元数据JSON',
  `last_sync_at` datetime(3) DEFAULT NULL COMMENT '最近同步时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `idx_mq_resource_unique` (`instance_id`, `resource_type`, `namespace`, `name`),
  KEY `idx_mq_resources_deleted_at` (`deleted_at`),
  KEY `idx_mq_resources_full_name` (`full_name`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ资源元数据';

CREATE TABLE IF NOT EXISTS `mq_bindings` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `vhost` varchar(255) DEFAULT NULL COMMENT 'vhost',
  `source` varchar(255) DEFAULT NULL COMMENT '源',
  `destination` varchar(255) DEFAULT NULL COMMENT '目标',
  `destination_type` varchar(40) DEFAULT NULL COMMENT '目标类型',
  `routing_key` varchar(255) DEFAULT NULL COMMENT '路由键',
  `arguments_json` text COMMENT '参数JSON',
  `last_sync_at` datetime(3) DEFAULT NULL COMMENT '最近同步时间',
  PRIMARY KEY (`id`),
  KEY `idx_mq_bindings_deleted_at` (`deleted_at`),
  KEY `idx_mq_bindings_instance_id` (`instance_id`),
  KEY `idx_mq_bindings_vhost` (`vhost`),
  KEY `idx_mq_bindings_source` (`source`),
  KEY `idx_mq_bindings_destination` (`destination`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ绑定关系';

CREATE TABLE IF NOT EXISTS `mq_consumer_groups` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `resource_id` bigint unsigned DEFAULT 0 COMMENT '资源ID',
  `group_name` varchar(255) NOT NULL COMMENT '消费组/订阅',
  `resource_name` varchar(512) DEFAULT '' COMMENT '资源名称',
  `namespace` varchar(255) DEFAULT '' COMMENT '命名空间',
  `state` varchar(80) DEFAULT NULL COMMENT '状态',
  `consumer_count` int DEFAULT 0 COMMENT '消费者数',
  `active_consumer_count` int DEFAULT 0 COMMENT '活跃消费者数',
  `current_offset` bigint DEFAULT 0 COMMENT '当前位点',
  `end_offset` bigint DEFAULT 0 COMMENT '结束位点',
  `lag` bigint DEFAULT 0 COMMENT 'Lag',
  `backlog` bigint DEFAULT 0 COMMENT '堆积',
  `last_consumed_at` datetime(3) DEFAULT NULL COMMENT '最近消费时间',
  `metadata_json` text COMMENT '元数据JSON',
  `last_sync_at` datetime(3) DEFAULT NULL COMMENT '最近同步时间',
  PRIMARY KEY (`id`),
  KEY `idx_mq_consumer_groups_instance_id` (`instance_id`),
  KEY `idx_mq_consumer_groups_group_name` (`group_name`),
  KEY `idx_mq_consumer_groups_resource_name` (`resource_name`(191)),
  KEY `idx_mq_consumer_groups_namespace` (`namespace`),
  KEY `idx_mq_consumer_groups_deleted_at` (`deleted_at`),
  KEY `idx_mq_consumer_groups_resource_id` (`resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ消费组/订阅元数据';

CREATE TABLE IF NOT EXISTS `mq_partitions` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `resource_id` bigint unsigned DEFAULT 0 COMMENT '资源ID',
  `resource_name` varchar(512) NOT NULL COMMENT '资源名称',
  `partition_id` int NOT NULL COMMENT '分区ID',
  `leader` varchar(255) DEFAULT NULL COMMENT 'Leader',
  `replicas_json` text COMMENT '副本JSON',
  `isr_json` text COMMENT 'ISR JSON',
  `start_offset` bigint DEFAULT 0 COMMENT '起始位点',
  `end_offset` bigint DEFAULT 0 COMMENT '结束位点',
  `current_offset` bigint DEFAULT 0 COMMENT '当前位点',
  `lag` bigint DEFAULT 0 COMMENT 'Lag',
  `status` varchar(80) DEFAULT NULL COMMENT '状态',
  `last_sync_at` datetime(3) DEFAULT NULL COMMENT '最近同步时间',
  PRIMARY KEY (`id`),
  KEY `idx_mq_partitions_instance_id` (`instance_id`),
  KEY `idx_mq_partitions_resource_name` (`resource_name`(191)),
  KEY `idx_mq_partitions_partition_id` (`partition_id`),
  KEY `idx_mq_partitions_deleted_at` (`deleted_at`),
  KEY `idx_mq_partitions_resource_id` (`resource_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ分区元数据';

CREATE TABLE IF NOT EXISTS `mq_sync_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `trigger_type` varchar(30) DEFAULT 'manual' COMMENT '触发类型',
  `status` varchar(30) DEFAULT 'running' COMMENT '状态',
  `started_at` datetime(3) DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `duration_ms` bigint DEFAULT 0 COMMENT '耗时毫秒',
  `broker_count` int DEFAULT 0 COMMENT 'Broker数',
  `resource_count` int DEFAULT 0 COMMENT '资源数',
  `consumer_group_count` int DEFAULT 0 COMMENT '消费组数',
  `partition_count` int DEFAULT 0 COMMENT '分区数',
  `message` varchar(500) DEFAULT NULL COMMENT '消息',
  `operator_id` bigint unsigned DEFAULT 0 COMMENT '操作人ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人',
  PRIMARY KEY (`id`),
  KEY `idx_mq_sync_jobs_deleted_at` (`deleted_at`),
  KEY `idx_mq_sync_jobs_instance_id` (`instance_id`),
  KEY `idx_mq_sync_jobs_status` (`status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ同步任务';

CREATE TABLE IF NOT EXISTS `mq_jobs` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `instance_name` varchar(100) DEFAULT NULL COMMENT '实例名称',
  `mq_type` varchar(30) DEFAULT NULL COMMENT 'MQ类型',
  `job_type` varchar(40) NOT NULL COMMENT '任务类型',
  `status` varchar(30) DEFAULT 'pending' COMMENT '状态',
  `progress_current` bigint DEFAULT 0 COMMENT '当前进度',
  `progress_total` bigint DEFAULT 0 COMMENT '总进度',
  `current_stage` varchar(120) DEFAULT NULL COMMENT '当前阶段',
  `trigger_type` varchar(30) DEFAULT 'manual' COMMENT '触发类型',
  `operator_id` bigint unsigned DEFAULT 0 COMMENT '操作人ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人',
  `started_at` datetime(3) DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `duration_ms` bigint DEFAULT 0 COMMENT '耗时毫秒',
  `message` varchar(500) DEFAULT NULL COMMENT '消息',
  `error_json` text COMMENT '错误JSON',
  `result_json` text COMMENT '结果JSON',
  `correlation_id` varchar(80) DEFAULT NULL COMMENT '链路ID',
  PRIMARY KEY (`id`),
  KEY `idx_mq_jobs_deleted_at` (`deleted_at`),
  KEY `idx_mq_jobs_instance_id` (`instance_id`),
  KEY `idx_mq_jobs_mq_type` (`mq_type`),
  KEY `idx_mq_jobs_job_type` (`job_type`),
  KEY `idx_mq_jobs_status` (`status`),
  KEY `idx_mq_jobs_operator_id` (`operator_id`),
  KEY `idx_mq_jobs_correlation_id` (`correlation_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ统一任务中心';

CREATE TABLE IF NOT EXISTS `mq_metric_snapshots` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned NOT NULL COMMENT '实例ID',
  `resource_id` bigint unsigned DEFAULT 0 COMMENT '资源ID',
  `resource_type` varchar(40) DEFAULT NULL COMMENT '资源类型',
  `resource_name` varchar(512) DEFAULT NULL COMMENT '资源名称',
  `broker_count` int DEFAULT 0 COMMENT 'Broker数',
  `online_broker_count` int DEFAULT 0 COMMENT '在线Broker数',
  `message_count` bigint DEFAULT 0 COMMENT '消息量',
  `backlog` bigint DEFAULT 0 COMMENT '堆积',
  `lag` bigint DEFAULT 0 COMMENT 'Lag',
  `produced_rate` double DEFAULT 0 COMMENT '生产速率',
  `consumed_rate` double DEFAULT 0 COMMENT '消费速率',
  `consumer_count` int DEFAULT 0 COMMENT '消费者数',
  `collected_at` datetime(3) DEFAULT NULL COMMENT '采集时间',
  PRIMARY KEY (`id`),
  KEY `idx_mq_metric_snapshots_deleted_at` (`deleted_at`),
  KEY `idx_mq_metric_snapshots_instance_id` (`instance_id`),
  KEY `idx_mq_metric_snapshots_resource_id` (`resource_id`),
  KEY `idx_mq_metric_snapshots_resource_type` (`resource_type`),
  KEY `idx_mq_metric_snapshots_resource_name` (`resource_name`),
  KEY `idx_mq_metric_snapshots_collected_at` (`collected_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ指标快照';

CREATE TABLE IF NOT EXISTS `mq_operation_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned DEFAULT 0 COMMENT '实例ID',
  `instance_name` varchar(100) DEFAULT NULL COMMENT '实例名称',
  `mq_type` varchar(30) DEFAULT NULL COMMENT 'MQ类型',
  `resource_type` varchar(40) DEFAULT NULL COMMENT '资源类型',
  `resource_name` varchar(512) DEFAULT NULL COMMENT '资源名称',
  `namespace` varchar(255) DEFAULT NULL COMMENT '命名空间',
  `action` varchar(80) DEFAULT NULL COMMENT '动作',
  `risk_level` varchar(30) DEFAULT NULL COMMENT '风险等级',
  `status` varchar(30) DEFAULT NULL COMMENT '状态',
  `request_json` text COMMENT '请求JSON',
  `result_json` text COMMENT '结果JSON',
  `reason` varchar(500) DEFAULT NULL COMMENT '原因',
  `operator_id` bigint unsigned DEFAULT 0 COMMENT '操作人ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人',
  `client_ip` varchar(80) DEFAULT NULL COMMENT '客户端IP',
  `started_at` datetime(3) DEFAULT NULL COMMENT '开始时间',
  `finished_at` datetime(3) DEFAULT NULL COMMENT '完成时间',
  `duration_ms` bigint DEFAULT 0 COMMENT '耗时毫秒',
  `message` varchar(500) DEFAULT NULL COMMENT '消息',
  PRIMARY KEY (`id`),
  KEY `idx_mq_operation_audits_deleted_at` (`deleted_at`),
  KEY `idx_mq_operation_audits_instance_id` (`instance_id`),
  KEY `idx_mq_operation_audits_mq_type` (`mq_type`),
  KEY `idx_mq_operation_audits_resource_type` (`resource_type`),
  KEY `idx_mq_operation_audits_resource_name` (`resource_name`),
  KEY `idx_mq_operation_audits_namespace` (`namespace`),
  KEY `idx_mq_operation_audits_action` (`action`),
  KEY `idx_mq_operation_audits_risk_level` (`risk_level`),
  KEY `idx_mq_operation_audits_status` (`status`),
  KEY `idx_mq_operation_audits_operator_id` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ操作审计';

CREATE TABLE IF NOT EXISTS `mq_message_audits` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `created_at` datetime(3) DEFAULT NULL,
  `updated_at` datetime(3) DEFAULT NULL,
  `deleted_at` datetime(3) DEFAULT NULL,
  `instance_id` bigint unsigned DEFAULT 0 COMMENT '实例ID',
  `mq_type` varchar(30) DEFAULT NULL COMMENT 'MQ类型',
  `resource_type` varchar(40) DEFAULT NULL COMMENT '资源类型',
  `resource_name` varchar(512) DEFAULT NULL COMMENT '资源名称',
  `namespace` varchar(255) DEFAULT NULL COMMENT '命名空间',
  `action` varchar(80) DEFAULT NULL COMMENT '动作',
  `sample_count` int DEFAULT 0 COMMENT '采样条数',
  `payload_bytes` int DEFAULT 0 COMMENT 'payload字节数',
  `filter_json` text COMMENT '过滤条件JSON',
  `status` varchar(30) DEFAULT NULL COMMENT '状态',
  `operator_id` bigint unsigned DEFAULT 0 COMMENT '操作人ID',
  `operator_name` varchar(100) DEFAULT NULL COMMENT '操作人',
  `client_ip` varchar(80) DEFAULT NULL COMMENT '客户端IP',
  `message` varchar(500) DEFAULT NULL COMMENT '消息',
  PRIMARY KEY (`id`),
  KEY `idx_mq_message_audits_deleted_at` (`deleted_at`),
  KEY `idx_mq_message_audits_instance_id` (`instance_id`),
  KEY `idx_mq_message_audits_mq_type` (`mq_type`),
  KEY `idx_mq_message_audits_resource_type` (`resource_type`),
  KEY `idx_mq_message_audits_resource_name` (`resource_name`),
  KEY `idx_mq_message_audits_namespace` (`namespace`),
  KEY `idx_mq_message_audits_action` (`action`),
  KEY `idx_mq_message_audits_status` (`status`),
  KEY `idx_mq_message_audits_operator_id` (`operator_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='MQ消息审计';

INSERT IGNORE INTO `sys_menu` (`id`, `name`, `code`, `type`, `parent_id`, `path`, `component`, `icon`, `sort`, `visible`, `status`, `created_at`, `updated_at`)
VALUES
  (68, '消息队列管理', 'asset_message_queues', 2, 15, '/asset/message-queues', 'asset/MessageQueueManagement', 'Connection', 8, 1, 1, NOW(), NOW()),
  (6801, 'MQ实例查看', 'messagequeue:instance:view', 3, 68, '', '', '', 1, 0, 1, NOW(), NOW()),
  (6802, 'MQ实例创建', 'messagequeue:instance:create', 3, 68, '', '', '', 2, 0, 1, NOW(), NOW()),
  (6803, 'MQ实例更新', 'messagequeue:instance:update', 3, 68, '', '', '', 3, 0, 1, NOW(), NOW()),
  (6804, 'MQ实例删除', 'messagequeue:instance:delete', 3, 68, '', '', '', 4, 0, 1, NOW(), NOW()),
  (6805, 'MQ实例启停', 'messagequeue:instance:status', 3, 68, '', '', '', 5, 0, 1, NOW(), NOW()),
  (6806, 'MQ连接测试', 'messagequeue:connection:test', 3, 68, '', '', '', 6, 0, 1, NOW(), NOW()),
  (6807, 'MQ元数据查看', 'messagequeue:metadata:view', 3, 68, '', '', '', 7, 0, 1, NOW(), NOW()),
  (6808, 'MQ元数据同步', 'messagequeue:metadata:sync', 3, 68, '', '', '', 8, 0, 1, NOW(), NOW()),
  (6809, 'MQ消费诊断', 'messagequeue:diagnosis:view', 3, 68, '', '', '', 9, 0, 1, NOW(), NOW()),
  (6810, 'MQ消息查看', 'messagequeue:message:read', 3, 68, '', '', '', 10, 0, 1, NOW(), NOW()),
  (6811, 'MQ消息导出', 'messagequeue:message:export', 3, 68, '', '', '', 11, 0, 1, NOW(), NOW()),
  (6812, 'MQ消息写入', 'messagequeue:message:write', 3, 68, '', '', '', 12, 0, 1, NOW(), NOW()),
  (6813, 'MQ资源管理', 'messagequeue:resource:manage', 3, 68, '', '', '', 13, 0, 1, NOW(), NOW()),
  (6814, 'MQ高危操作', 'messagequeue:operation:high-risk', 3, 68, '', '', '', 14, 0, 1, NOW(), NOW()),
  (6815, 'MQ审计查看', 'messagequeue:audit:view', 3, 68, '', '', '', 15, 0, 1, NOW(), NOW()),
  (6816, 'MQ审计导出', 'messagequeue:audit:export', 3, 68, '', '', '', 16, 0, 1, NOW(), NOW()),
  (6817, 'MQ实例权限管理', 'messagequeue:permission:manage', 3, 68, '', '', '', 17, 0, 1, NOW(), NOW());

INSERT IGNORE INTO `sys_role_menu` (`role_id`, `menu_id`)
VALUES
  (1, 68), (1, 6801), (1, 6802), (1, 6803), (1, 6804), (1, 6805), (1, 6806), (1, 6807), (1, 6808),
  (1, 6809), (1, 6810), (1, 6811), (1, 6812), (1, 6813), (1, 6814), (1, 6815), (1, 6816), (1, 6817);

SET FOREIGN_KEY_CHECKS = 1;
